[package]
name = "polkadot_final3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
substrate-subxt = "0.16.0"
hex = "0.4.3"